### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [creutis/teacozy#4]
Grade: Exceeds Expectations

This is a fantastic take on the project! You've effectively included all of the necessary elements and coded in a style that is very easy to follow and understand. This is due to your consistent alignment and formatting techniques as well as the comments that you left in the HTML file. You have a great handle on how to apply classes and ids, and when to use which. 

Moving forward, I encourage you to also comment your CSS file. You can organize the stylings by section of the app to which they're applied, and leaving a comment delineating which section is which will make that file easier to read through and understand. Also, feel free to take liberties with your CSS to make your project more visually engaging. A few resources to help you do that are Google Fonts for finding cool fonts, and Coolors.co, which generates free color palettes to implement in your design. You might find those fun to play with, and they'll help you infuse your apps with your own style. Again, great job and congratulations!

**Comment by creutis** [comment]
Thank you so much for your comment, great comment regarding the documentation off the css as well - that would also help with the learning as well!
